version: '3.7'

networks:
  ogcapi:
    name: ogcapi

services:
  traefik:
    image: "traefik:v2.8"
    container_name: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - ogcapi
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  gdal:
    image: osgeo/gdal:latest
    container_name: gdal
    volumes:
      - ../version/data:/tmp/data
    networks:
      - ogcapi
    command: bash

  pygeoapi:
    image: geopython/pygeoapi:latest
    container_name: pygeoapi
    ports:
      - 5000:80
    expose:
      - "5000"
    volumes:
      - ./config/pygeoapi.config.yml:/pygeoapi/local.config.yml
      - ./custom_data:/data
    networks:
      - ogcapi
    restart: always
    environment:
      - SCRIPT_NAME=/geoapi
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pygeoapi.entrypoints=web"
      - traefik.http.routers.pygeoapi.rule=PathPrefix("/geoapi")
      # - "traefik.http.routers.pygeoapi.rule=Host(`localhost`)"
      # - "traefik.http.services.pygeoapi.loadbalancer.server.port=80"
  